/**
 * ==========================================================================
 * NexusAI - Backend Server (Node.js & Express with Google Gemini API)
 * 
 * Uses the official Google Gemini SDK (@google/genai) and gemini-3.6-flash.
 * ==========================================================================
 */

// 1. Load environment variables from backend/.env
require('dotenv').config();

// 2. Import required packages
const express = require('express');
const cors = require('cors');
const { GoogleGenAI } = require('@google/genai');

// 3. Initialize the Express application
const app = express();

// 4. Port configuration
const PORT = process.env.PORT || 5000;

// ==========================================================================
// Middleware Configuration
// ==========================================================================

// Enable CORS so your frontend can communicate with this server
app.use(cors());

// Parse incoming JSON request payloads
app.use(express.json());

// ==========================================================================
// API Routes
// ==========================================================================

/**
 * GET /
 * Health check endpoint confirming server and model status.
 */
app.get('/', (req, res) => {
    const isApiKeyConfigured = Boolean(
        process.env.GEMINI_API_KEY && 
        process.env.GEMINI_API_KEY !== 'your_gemini_api_key_here'
    );

    res.status(200).json({
        status: 'online',
        message: 'NexusAI Backend Server is running!',
        geminiConfigured: isApiKeyConfigured,
        model: process.env.GEMINI_MODEL || 'gemini-3.6-flash',
        timestamp: new Date().toISOString()
    });
});

/**
 * POST /api/chat
 * Main chat endpoint: Receives user message, calls Gemini API, and returns reply.
 * Expects JSON body: { "message": "User query" }
 */
app.post('/api/chat', async (req, res) => {
    try {
        const { message, model } = req.body;

        // --- STEP 1: Input Validation ---
        if (!message || typeof message !== 'string' || message.trim().length === 0) {
            return res.status(400).json({
                success: false,
                error: 'Validation failed: A non-empty "message" string is required in the request body.'
            });
        }

        const trimmedMessage = message.trim();

        // --- STEP 2: Validate Gemini API Key in .env ---
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey || apiKey === 'your_gemini_api_key_here') {
            console.warn('⚠️ Gemini API Key is missing in backend/.env');
            return res.status(400).json({
                success: false,
                error: 'Gemini API Key is missing! Please open "backend/.env" and replace "your_gemini_api_key_here" with your actual Gemini API key from https://aistudio.google.com/.'
            });
        }

        // --- STEP 3: Initialize Google Gemini AI Client ---
        const ai = new GoogleGenAI({ apiKey });
        let modelName = process.env.GEMINI_MODEL || 'gemini-3.6-flash';
        if (typeof model === 'string' && model.trim().length > 0) {
            const m = model.trim().toLowerCase();
            if (m === 'fast') modelName = 'gemini-3.6-flash';
            else if (m === 'balanced') modelName = 'gemini-1.5-pro';
            else if (m === 'creative') modelName = 'gemini-1.5-pro';
            else modelName = model.trim();
        }

        console.log(`[Gemini API] Sending prompt to ${modelName}: "${trimmedMessage}"`);

        // --- STEP 4: Generate Content from Gemini ---
        const response = await ai.models.generateContent({
            model: modelName,
            contents: trimmedMessage
        });

        const replyText = response.text || 'No response generated by the model.';

        console.log(`[Gemini API] Response received successfully (${replyText.length} chars)`);

        // --- STEP 5: Return JSON Response to Frontend ---
        return res.status(200).json({
            success: true,
            userMessage: trimmedMessage,
            reply: replyText,
            model: modelName,
            timestamp: new Date().toISOString()
        });

    } catch (error) {
        console.error('Error communicating with Google Gemini API:', error);

        // Check for specific authentication / quota errors
        const errorMessage = error.message || 'Failed to generate response from Gemini API';
        
        let statusCode = 500;
        if (errorMessage.includes('API_KEY_INVALID') || errorMessage.includes('401') || errorMessage.includes('unauthorized')) {
            statusCode = 401;
        }

        return res.status(statusCode).json({
            success: false,
            error: `Gemini API Error: ${errorMessage}`
        });
    }
});

// ==========================================================================
// 404 Route Handler
// ==========================================================================
app.use((req, res) => {
    res.status(404).json({
        success: false,
        error: `Cannot ${req.method} ${req.originalUrl}. Route not found.`
    });
});

// ==========================================================================
// Start server locally
// ==========================================================================

if (require.main === module) {
    app.listen(PORT, () => {
        console.log(`===========================================`);
        console.log(`🚀 NexusAI Backend is running on port ${PORT}`);
        console.log(`🤖 Powered by Google Gemini (${process.env.GEMINI_MODEL || 'gemini-3.6-flash'})`);
        console.log(`🔗 Health Check: http://localhost:${PORT}/`);
        console.log(`💬 Chat API:     http://localhost:${PORT}/api/chat`);
        console.log(`===========================================`);
    });
}

// Export Express app for Vercel
module.exports = app;